spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: microconfig-test-client6

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:admin@localhost:7301/eureka
  register-with-eureka: false

info:
  app.name: cwcloudapp
  company.name: 北京陈伟科技
---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: microconfig-test-client6

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:admin@localhost:7301/eureka
  register-with-eureka: false
  
info:
  app.name: microcloud-config-client-beta2
  company.name: enjoy